PROJECT: 'bitrap_gmm_eth'
VISUALIZE: True
CKPT_DIR: 'checkpoints/ETH_UCY_checkpoints' 
OUT_DIR: 'outputs/ETH_UCY_outputs'
DEVICE: 'cuda'
METHOD: 'BiTraPGMM'
MODEL:
  PRED_GLOBAL: False # we predict residual and shift to global later.
  IMG_SIZE: (256,256)
  GOAL_MAP_SIZE: (128, 128)
  UNIT_PRIOR: False
  BEST_OF_MANY: True
  K: 20
  LATENT_DIST: 'categorical' #'gaussian' #
  LATENT_DIM: 25 #32 #
  REFINE_GOAL: True
  PER_STEP_TYPE: 'vel_gmm'
  SAMPLE_BACK_INPUT: True
  DEC_WITH_Z: True
  BACKWARD_INPUT: 'merge'
  FUTURE_TYPE: 'traj'
  REVERSE_LOSS: True 
  Z_CLIP: True

  dt: 0.4
  INPUT_LEN: 8
  PRED_LEN: 12 # input and pred_len is defined in 30FPS
  GLOBAL_INPUT_DIM: 6
  DEC_INPUT_DIM: 2 # extra input is added to the decoder, just like the egomotion in our FOL, if it's speed, DEC_INPUT_DIM=1
  DEC_OUTPUT_DIM: 2 
  DROPOUT: 0.25
  
  ENC_CONCAT_TYPE: 'average'
  INPUT_EMBED_SIZE: 256
  FLOW_EMBED_SIZE: 256
  FLOW_HIDDEN_SIZE: 256
  ENC_HIDDEN_SIZE: 256
  DEC_INPUT_SIZE: 256
  DEC_HIDDEN_SIZE: 256
  # SEG_LEN: 15
DATASET:
  NAME: 'eth'
  ETH_CONFIG: 'configs/ETH_UCY.json'
  ROOT: 'data/ETH_UCY_trajectron/'
  TRAJECTORY_PATH: 'data/ETH_UCY_trajectron/trajectories/'
  BBOX_TYPE: 'none'
  NORMALIZE: 'none'

DATALOADER:
  NUM_WORKERS: 24
SOLVER:
  # TRAIN_MODULE: 'FOL'
  MAX_EPOCH: 50
  BATCH_SIZE: 128
  LR: 0.001
  scheduler: 'exp'
  GAMMA: 0.999
TEST:
  BATCH_SIZE: 128
  KDE_BATCH_SIZE: 24