PROJECT: 'concat_unimodal_JAAD'
CKPT_DIR: 'checkpoints/JAAD_checkpoints/traj_checkpoints/' 
OUT_DIR: 'outputs/JAAD_outputs/traj_outputs'
DEVICE: 'cuda'
METHOD: 'TransPredict_Unimodal'
VISUALIZE: True
MODEL:
  IMG_SIZE: (256,256)
  BEST_OF_MANY: True
  K: 1
  LATENT_DIST: 'gaussian' 
  LATENT_DIM: 0 

  PRED_LEN: 45 # input and pred_len is defined in 30FPS
  GLOBAL_EMBED_SIZE: 272
  GLOBAL_HIDDEN_SIZE:  272
  GLOBAL_INPUT_DIM: 4    # should be modified to 6 for PIE dataset
  DROPOUT: 0.0
  
  ENC_CONCAT_TYPE: 'average'
  INPUT_EMBED_SIZE: 272
  FLOW_EMBED_SIZE: 272
  FLOW_HIDDEN_SIZE: 272
  ENC_HIDDEN_SIZE: 272    # original: 256
  DEC_INPUT_SIZE: 272
  DEC_HIDDEN_SIZE: 272
  DEC_OUTPUT_DIM: 4
  ATTRIB_FEAT_TYPE: 'simple'
  INTENT_OUT_DIM: 3
  DECODER_TYPE: 'bezier_curve'
  USE_MODALITY_ATTEN: False
DATASET:
  NAME: 'JAAD'
  ROOT: '/home/suzx/new_disks/eclipse_ws2/JAAD/JAAD-JAAD_2.0'
  TRAJECTORY_PATH: '/home/suzx/new_disks/eclipse_ws2/JAAD/JAAD-JAAD_2.0/data_cache/trajectory'
  IMG_FEAT_SAVE_ROOT: '/home/suzx/new_disks/eclipse_ws2/JAAD/JAAD-JAAD_2.0/img_feat_cache/trajectory'
  BODY_ORI_SAVE_ROOT: '/home/suzx/new_disks/eclipse_ws2/JAAD/JAAD-JAAD_2.0/body_ori_cache/trajectory'
  POSE_FEAT_SAVE_ROOT: '/home/suzx/new_disks/eclipse_ws2/JAAD/JAAD-JAAD_2.0/pose_feat_cache/trajectory'
  BBOX_TYPE: 'cxcywh' # bbox is in cxcywh format
  NORMALIZE: 'zero-one' 
  MIN_BBOX: [0,0,0,0] # the min of cxcywh or x1x2y1y2
  MAX_BBOX: [1920, 1080, 1920, 1080] # the max of cxcywh or x1x2y1y2
  SEQ_TYPE: 'trajectory'
DATALOADER:
  NUM_WORKERS: 1    # should not be too large (original: 24)
SOLVER:
  MAX_EPOCH: 100
  BATCH_SIZE: 128    # should not be too large (original: 128)
  LR: 0.001
  scheduler: 'plateau'
TEST:
  BATCH_SIZE: 128    # should not be too large (original: 1024)
VIZ:
  TRAJ_VIZ_SAVE_ROOT: '/home/suzx/new_disks/eclipse_ws2/JAAD/JAAD-JAAD_2.0/visualize_results/unimodal/concat'